USER_DETAILS_BASE_URL = "https://api.github.com"
USER_DETAILS_API_ROUTE = "/user"
ACCESS_TOKEN_BASE_URL = "https://github.com"
ACCESS_TOKEN_API_ROUTE = "/login/oauth/access_token"
CLIENT_ID = ""
CLIENT_SECRET = ""
